	soc_system u0 (
		.clk_clk                     (<connected-to-clk_clk>),                     //        clk.clk
		.clk_25mhz_clk               (<connected-to-clk_25mhz_clk>),               //  clk_25mhz.clk
		.hps_io_hps_io_usb1_inst_D0  (<connected-to-hps_io_hps_io_usb1_inst_D0>),  //     hps_io.hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1  (<connected-to-hps_io_hps_io_usb1_inst_D1>),  //           .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2  (<connected-to-hps_io_hps_io_usb1_inst_D2>),  //           .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3  (<connected-to-hps_io_hps_io_usb1_inst_D3>),  //           .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4  (<connected-to-hps_io_hps_io_usb1_inst_D4>),  //           .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5  (<connected-to-hps_io_hps_io_usb1_inst_D5>),  //           .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6  (<connected-to-hps_io_hps_io_usb1_inst_D6>),  //           .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7  (<connected-to-hps_io_hps_io_usb1_inst_D7>),  //           .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK (<connected-to-hps_io_hps_io_usb1_inst_CLK>), //           .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP (<connected-to-hps_io_hps_io_usb1_inst_STP>), //           .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR (<connected-to-hps_io_hps_io_usb1_inst_DIR>), //           .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT (<connected-to-hps_io_hps_io_usb1_inst_NXT>), //           .hps_io_usb1_inst_NXT
		.hps_io_hps_io_uart0_inst_RX (<connected-to-hps_io_hps_io_uart0_inst_RX>), //           .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX (<connected-to-hps_io_hps_io_uart0_inst_TX>), //           .hps_io_uart0_inst_TX
		.memory_mem_a                (<connected-to-memory_mem_a>),                //     memory.mem_a
		.memory_mem_ba               (<connected-to-memory_mem_ba>),               //           .mem_ba
		.memory_mem_ck               (<connected-to-memory_mem_ck>),               //           .mem_ck
		.memory_mem_ck_n             (<connected-to-memory_mem_ck_n>),             //           .mem_ck_n
		.memory_mem_cke              (<connected-to-memory_mem_cke>),              //           .mem_cke
		.memory_mem_cs_n             (<connected-to-memory_mem_cs_n>),             //           .mem_cs_n
		.memory_mem_ras_n            (<connected-to-memory_mem_ras_n>),            //           .mem_ras_n
		.memory_mem_cas_n            (<connected-to-memory_mem_cas_n>),            //           .mem_cas_n
		.memory_mem_we_n             (<connected-to-memory_mem_we_n>),             //           .mem_we_n
		.memory_mem_reset_n          (<connected-to-memory_mem_reset_n>),          //           .mem_reset_n
		.memory_mem_dq               (<connected-to-memory_mem_dq>),               //           .mem_dq
		.memory_mem_dqs              (<connected-to-memory_mem_dqs>),              //           .mem_dqs
		.memory_mem_dqs_n            (<connected-to-memory_mem_dqs_n>),            //           .mem_dqs_n
		.memory_mem_odt              (<connected-to-memory_mem_odt>),              //           .mem_odt
		.memory_mem_dm               (<connected-to-memory_mem_dm>),               //           .mem_dm
		.memory_oct_rzqin            (<connected-to-memory_oct_rzqin>),            //           .oct_rzqin
		.onchip_mem_address          (<connected-to-onchip_mem_address>),          // onchip_mem.address
		.onchip_mem_chipselect       (<connected-to-onchip_mem_chipselect>),       //           .chipselect
		.onchip_mem_clken            (<connected-to-onchip_mem_clken>),            //           .clken
		.onchip_mem_write            (<connected-to-onchip_mem_write>),            //           .write
		.onchip_mem_readdata         (<connected-to-onchip_mem_readdata>),         //           .readdata
		.onchip_mem_writedata        (<connected-to-onchip_mem_writedata>),        //           .writedata
		.reset_reset_n               (<connected-to-reset_reset_n>)                //      reset.reset_n
	);

