transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib soc_system
vmap soc_system soc_system
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_mm_interconnect_0.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_pll_0.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_onchip_memory2_0.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_hps_0.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_hps_0_hps_io.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/hps_sdram.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_mem_if_hhp_qseq_synth_top.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_addr_cmd_pads.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_io_pads.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_memphy.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/hps_sdram_p0_acv_ldc.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/hps_sdram_p0_altdqdqs.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/hps_sdram_p0_clock_pair_generator.v}
vlog -vlog01compat -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/hps_sdram_p0_generic_ddio.v}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_merlin_address_alignment.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_merlin_burst_adapter_13_1.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_002.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_merlin_axi_master_ni.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altdq_dqs2_acv_connect_to_hard_phy_cyclonev.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_mem_if_dll_cyclonev.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_mem_if_hard_memory_controller_top_cyclonev.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/altera_mem_if_oct_cyclonev.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/hps_sdram_p0.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/hps_sdram_pll.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_hps_0_hps_io_border.sv}
vlog -sv -work soc_system +incdir+C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/submodules/soc_system_hps_0_fpga_interfaces.sv}
vcom -93 -work work {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/sync_generator.vhd}
vcom -93 -work work {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/font_rom.vhd}
vcom -93 -work soc_system {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/soc_system/synthesis/soc_system.vhd}
vcom -93 -work work {C:/Users/Eriks/Documents/fpga_soc/project/pls/emils_eriks_70s/top.vhd}

